homepage:
    path:      /{_locale}
    defaults:  { _controller: OktolabIntakeBundle:Default:index, _locale: de }
    requirements:
        _locale:  de|en

oktolab_intake_homepage:
    resource: "@OktolabIntakeBundle/Controller/"
    type:     annotation
    prefix: /{_locale}
    requirements:
        _locale: de|en