services:
    oktolab.upload_listener:
        class:     Oktolab\IntakeBundle\Model\jQueryUploadService
        arguments: [ @doctrine.orm.entity_manager, @bprs_user.mailer ]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: uploadedFile }
            - { name: kernel.event_listener, event: oneup_uploader.pre_upload, method: onUpload }

    oktolab.locale_listener:
        class:     Oktolab\IntakeBundle\Model\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    oktolab.filesizeExtension:
        class:     Oktolab\IntakeBundle\Extension\FilesizeExtension
        tags:
            - { name: twig.extension }