start:
    path:      /
    defaults:  { _controller: AppBundle:Default:index, _locale: de }
    requirements:
        _locale:  de|en

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    defaults:  { _locale: de } #new
    prefix: /{_locale}
    requirements:
        _locale: de|en

bprs_user:
    resource: .
    type: bprs_user

bprs_asset:
    resource: .
    type: bprs_asset

oneup_uploader:
    resource: .
    type: uploader
