security:
    encoders:
        Oktolab\IntakeBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: OktolabIntakeBundle:User }

    firewalls:
        admin_area:
            pattern:    /backend
            http_basic: ~

    access_control:
        - { path: /backend, roles: ROLE_ADMIN }

