security:

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    encoders:
        Oktolab\IntakeBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        database:
            entity: 
                class: OktolabIntakeBundle:User
                property: username

    firewalls:
        admin_area:
            pattern:    /backend
            http_basic: ~
            form_login:
                login_path: intake_login
                check_path: intake_login_check
                #csrf_provider: form.csrf_provider
                default_target_path: /de
            logout: 
                path: oktolab_intake_logout
                target: /de

    access_control:
        - { path: /backend, roles: ROLE_USER }
        - { path: /backend/admin, roles: ROLE_ADMIN}

