security:

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    encoders:
        Oktolab\IntakeBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        database:
            entity: 
                class: OktolabIntakeBundle:User
                property: username

    firewalls:
        admin_area:
            pattern:    /backend
            http_basic: ~
            logout:
                path:   /logout
                target: /de

    access_control:
        - { path: /backend, roles: ROLE_USER }
        - { path: /backend/admin, roles: ROLE_ADMIN}

