security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    encoders:
        Bprs\UserBUndle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        database:
            entity: 
                class: BprsUserBundle:User

    firewalls:
        main:
            pattern:    /
            http_basic: ~
            form_login:
                login_path: bprs_user_login
                check_path: bprs_user_login_check
                default_target_path: intake_backend
                csrf_provider: form.csrf_provider
                default_target_path: /de
            logout: 
                path: bprs_user_logout
                target: /de
            anonymous: ~

    access_control:
        - { path: /backend, roles: ROLE_USER }
        - { path: /backend/admin, roles: ROLE_ADMIN}
